import type { ResearchPayload } from "./research";

export type TabId = "research" | "rehearse" | "relive";
export type AnswerMode = "voice" | "text";
export type ResearchStep = "job" | "company" | "news";

/** Lifecycle of a dossier's prep brief. "ready" means brief is displayable and
 *  cached — re-expanding a ready dossier never regenerates it. */
export type BriefStatus = "idle" | "generating" | "ready" | "failed";

/** One of the three research cards inside a dossier. */
export interface DossierCard {
  step: ResearchStep;
  state: "pending" | "ok" | "error";
  payload?: ResearchPayload;
  /** The edge function's fetched_at — the original fetch time, even for cache hits. */
  freshAt?: string;
  /** True when this payload came from the in-memory or database cache. */
  cached?: boolean;
}

/** One line of the prep brief, traceable to the card it came from. */
export interface BriefClaim {
  text: string;
  /** The research card this claim is grounded in. */
  source: ResearchStep;
  /** Long-form text (e.g. the job description) — rendered collapsed, expandable. */
  long?: boolean;
}

export interface BriefSection {
  heading: string;
  claims: BriefClaim[];
}

/** A complete, expandable research file for one job posting. */
export interface Dossier {
  id: string;
  jobTitle: string;
  company: string;
  jobUrl: string;
  createdAt: number;
  cards: DossierCard[];
  /** Generated from the cards; each claim cites its source card. */
  brief: BriefSection[];
  /** Lifecycle of the brief — "ready" means it is displayable and cached. */
  briefStatus?: BriefStatus;
  /** True when the brief was generated by the AI model (vs the evidence fallback). */
  briefFromAi?: boolean;
  /** Plain-language note rendered with the brief (e.g. which cards failed). */
  briefNote?: string;
  /** Resume measured against this posting. Absent when no resume is saved. */
  fit?: FitMatch;
  fitStatus?: FitMatchStatus;
  /** Fingerprint of the resume this fit was computed from. Lets a saved,
   *  replaced or deleted resume backfill dossiers already on screen instead of
   *  leaving them matched against a resume that no longer exists. */
  fitKey?: string;
}

/** The user's resume, stored against their (currently anonymous) account.
 *  One per user — "your resume", singular. Plain text only; see resume.ts. */
export interface Resume {
  content: string;
  fileName?: string;
  updatedAt: number;
}

/** One observation in a fit match, quoting the evidence it rests on. */
export interface FitMatchItem {
  text: string;
  /** The phrase from the posting or the resume this rests on. */
  evidence?: string;
}

/** Resume measured against one posting. Generated, never stored. */
export interface FitMatch {
  /** What the candidate already has that the posting asks for. */
  strengths: FitMatchItem[];
  /** What the posting asks for that the resume does not evidence. */
  gaps: FitMatchItem[];
  /** Ordered — the first item is what to study first. */
  studyPlan: string[];
  /** One line: how well this candidate fits this posting, and why. */
  verdict?: string;
}

export type FitMatchStatus = "idle" | "generating" | "ready" | "failed";

export interface Persona {
  id: string;
  label: string;
  /** Full name — shown beside the speaking indicator ("Priya Nair · Hiring Manager · Deltek"). */
  name: string;
  voice: string;
}

/** Gender choice for the interviewer, picked on the setup screen. */
export type InterviewerGender = "random" | "female" | "male";

/** One drawable interviewer identity. `voice` is a Speechmatics TTS id and
 *  always matches the pool's gender (male → theo/jack, female → sarah/megan).
 *  One interviewer is drawn when the interview begins and held for the whole
 *  session — there is no per-question rotation. */
export interface Interviewer {
  id: string;
  name: string;
  voice: string;
}

/** Female name pool. Voices alternate sarah (English female, UK) and megan
 *  (English female, US) — see the Speechmatics TTS catalogue. Origins are
 *  deliberately varied; the pool is never a wall of Anglo names. */
export const FEMALE_INTERVIEWERS: Interviewer[] = [
  { id: "f1", name: "Priya Nair", voice: "sarah" },
  { id: "f2", name: "Ling Zhao", voice: "megan" },
  { id: "f3", name: "Carmen Delgado", voice: "sarah" },
  { id: "f4", name: "Yuki Tanaka", voice: "megan" },
  { id: "f5", name: "Aisha Bello", voice: "sarah" },
  { id: "f6", name: "Beatriz Oliveira", voice: "megan" },
  { id: "f7", name: "Ingrid Larsson", voice: "sarah" },
  { id: "f8", name: "Naledi Mokoena", voice: "megan" },
  { id: "f9", name: "Fatima Al-Rashid", voice: "sarah" },
  { id: "f10", name: "Anja Kovac", voice: "megan" },
  { id: "f11", name: "Chloe Dubois", voice: "sarah" },
  { id: "f12", name: "Olga Sokolova", voice: "megan" },
];

/** Male name pool. Voices alternate theo (English male, UK) and jack (English
 *  male, US) — the catalogue's second male voice, so the male pool is not a
 *  single voice. Origins are deliberately varied; never a wall of Anglo names. */
export const MALE_INTERVIEWERS: Interviewer[] = [
  { id: "m1", name: "Arjun Mehta", voice: "theo" },
  { id: "m2", name: "Wei Chen", voice: "jack" },
  { id: "m3", name: "Mateo Alvarez", voice: "theo" },
  { id: "m4", name: "Kenji Nakamura", voice: "jack" },
  { id: "m5", name: "Oumar Diallo", voice: "theo" },
  { id: "m6", name: "Diego Ferreira", voice: "jack" },
  { id: "m7", name: "Jonas Weber", voice: "theo" },
  { id: "m8", name: "Kofi Mensah", voice: "jack" },
  { id: "m9", name: "Youssef Haddad", voice: "theo" },
  { id: "m10", name: "Emil Lindqvist", voice: "jack" },
  { id: "m11", name: "Tomasz Nowak", voice: "theo" },
  { id: "m12", name: "Dimitri Petrov", voice: "jack" },
];

/** A point a strong answer should hit. `facts` are the matchable tokens. */
export interface KeyPoint {
  label: string;
  facts: string[];
}

export interface InterviewQuestion {
  id: string;
  /** What the candidate reads on screen. */
  text: string;
  /**
   * What the panel says aloud. Text-to-speech reads literally, so "10+ yrs",
   * "AEM/CQ" and "CI/CD" all come out wrong. The model emits this expanded —
   * it is never derived in JavaScript. Falls back to `text` when absent.
   */
  speechText?: string;
  keyPoints: KeyPoint[];
  modelAnswer: string;
  sourceCard: ResearchStep;
  sourceLabel: string;
}

export interface RubricScore {
  label: string;
  score: number; // 1–5
}

/** One question's outcome inside a completed session. */
export interface AnswerRecord {
  questionId: string;
  questionText: string;
  /** The dossier card (job/company/news) this question was grounded in. */
  sourceCard: ResearchStep;
  skipped: boolean;
  transcript: string;
  blobUrl?: string;
  fileName?: string;
  durationMs: number;
  content: RubricScore[];
  delivery: RubricScore[];
  missed: string[];
  modelAnswer: string;
  sourceLabel: string;
}

export interface SessionSummary {
  total: number;
  answered: number;
  skipped: number;
  totalMs: number;
  avgContent: number;
  avgDelivery: number;
  /** Total key points missed across the session's answered questions. */
  missedTotal: number;
}

/** A completed rehearsal, kept in memory for the Relive tab. */
export interface Session {
  id: string;
  dossierId: string;
  jobTitle: string;
  company: string;
  persona: Persona;
  startedAt: number;
  completedAt: number;
  answers: AnswerRecord[];
  /** Set only when the user opted into server-side recording storage — drives
   *  the Relive session code + deletion copy. In-memory sessions never set it. */
  storageCode?: string;
  summary: SessionSummary;
}
